#!/bin/sh
#
#
# sapdb		SAP DB
#
# chkconfig:	35 95 01
# description:	Startup/shutdown script for SAP DB
#

# Source function library
. /etc/rc.d/init.d/functions

# Get network config
. /etc/sysconfig/network

# Get service config - may override defaults
[ -f /etc/sysconfig/sapdb ] && . /etc/sysconfig/sapdb

# Check that networking is up.
if is_yes "${NETWORKING}"; then
	if [ ! -f /var/lock/subsys/network -a "$1" != stop -a "$1" != status ]; then
		msg_network_down SAP DB
		exit 1
	fi
else
	exit 0
fi

# where to find x_server executable
IND_PROG_DBROOT="/usr/lib/sapdb/indep_prog"
X_PATH=$IND_PROG_DBROOT/bin
X_SERVER=$X_PATH/x_server
DBMCLI=$X_PATH/dbmcli
VSERVER=$IND_PROG_DBROOT/pgm/vserver

test -x $X_SERVER || exit 1

RETVAL=0
case "$1" in
  start)
	# Check if the service is already running?
	if [ ! -f /var/lock/subsys/sapdb ]; then
		msg_starting "SAPDB communication server"
		SHMMAX=`/sbin/sysctl -n kernel.shmmax`
		if [ $SHMMAX -lt 104857600 ]; then
			/sbin/sysctl -e -w kernel.shmmax=104857600 > /dev/null 2>&1
		fi

		daemon --user sapdb "$X_SERVER start >/dev/null 2>&1"

		RETVAL=$?
		[ $RETVAL -eq 0 ] && touch /var/lock/subsys/sapdb
		for inst in $SAPDB_INSTANCES; do
 			DB=${inst%%,*}
			DBM=${inst#*,}
			msg_starting $(nls "SAPDB instance %s" "$DB")
			busy
			$DBMCLI -d $DB -u $DBM db_warm > /dev/null &
			RET=$?
			[ $RET -eq 0 ] && ok || fail
			[ $RETVAL -eq 0 ] && RETVAL=$RET
		done
	else
		msg_already_running "SAPDB communication server"
	fi
	;;
  stop)
	# Stop daemons.
	if [ -f /var/lock/subsys/sapdb ]; then
		for inst in $SAPDB_INSTANCES; do
			DB=${inst%%,*}
			DBM=${inst#*,}
			msg_stopping $(nls "SAPDB instance %s" "$DB")
			busy
			$DBMCLI -d $DB -u $DBM db_offline > /dev/null
			RET=$?
			[ $RET -eq 0 ] && ok || died
			[ $RETVAL -eq 0 ] && RETVAL=$RET
		done
		msg_stopping "SAPDB communication server"
		busy
		$X_SERVER stop > /dev/null 2>&1
		RET=$?
		[ $RET -eq 0 ] && ok || died
		[ $RETVAL -eq 0 ] && RETVAL=$RET
		rm -f /var/lock/subsys/sapdb >/dev/null 2>&1
	else
		msg_not_running "SAPDB communication server"
	fi
	;;
  status)
	status sapdb
	exit $?
	;;
  restart|force-reload)
	$0 stop
	$0 start
	exit $?
	;;
  *)
	msg_usage "$0 {start|stop|restart|force-reload|status}"
	exit 3
esac

exit $RETVAL
